# Generated by Django 5.2 on 2025-10-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='playlistThumbnail/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visi', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=23)),
            ],
        ),
    ]
