# Generated by Django 5.2 on 2025-10-16 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0002_playlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='videoThumbnail/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('visi', models.BooleanField(default=True)),
                ('tviews', models.PositiveIntegerField(default=0)),
                ('tlikes', models.PositiveIntegerField(default=0)),
                ('slug', models.CharField(blank=True, max_length=23)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('categories', models.CharField(max_length=350)),
                ('categoryId', models.PositiveBigIntegerField(blank=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist', to='opcoder.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoComment', to='opcoder.video')),
            ],
        ),
    ]
