# Generated by Django 5.2 on 2025-10-16 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcoder', '0003_video_videocomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('BUG', 'Technical Bug Report'), ('FEATURE', 'Feature Request / Suggestion'), ('UI', 'UI/UX Improvement'), ('CONTENT', 'Content Quality/Correction'), ('GENERAL', 'General Inquiry/Praise')], default='GENERAL', max_length=10)),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Dissatisfied'), (2, '2 - Dissatisfied'), (3, '3 - Neutral'), (4, '4 - Satisfied'), (5, '5 - Very Satisfied')], default=5, help_text="User's satisfaction rating (1 to 5 stars).")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes on resolution or triage.', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-date'],
            },
        ),
    ]
